import { Component } from '@angular/core';
import { Observable, of } from 'rxjs';

@Component({
  selector: 'app-table-demo1',
  templateUrl: './table-demo1.component.html',
  styleUrls: ['./table-demo1.component.scss'],
})
export class TableDemo1Component {
  displayedColumns: any[] = [
    'Full Name',
    'Job Title',
    'Country',
    'Status',
    'Phone',
    'Email',
    'Address',
    'LinkedIn',
    'Twitter',
    'Instagram',
  ];
  ngxBordered: boolean = true;

  values(): Observable<any[]> {
    const values: {
      picture: string;
      full_name: string;
      job_title: string;
      country: string;
      status: string;
      phone: string;
      email: string;
      address: string;
      linkedIn: string;
      twitter: string;
      instagram: string;
    }[] = [
      {
        picture: '/assets/images/avatar/man.png',
        full_name: 'Emily Thompson',
        job_title: 'Graphic Designer',
        country: 'ca',
        status: 'Active',
        phone: '444-789-0123',
        email: 'emily.thompson@example.com',
        address: '101 Pine St, City, Province',
        linkedIn: 'linkedin.com/in/emilythompson',
        twitter: '@emilythompson',
        instagram: '@emilythompson_insta',
      },
      {
        picture: '',
        full_name: 'Robert Davis',
        job_title: 'Financial Analyst',
        country: 'us',
        status: 'Active',
        phone: '555-666-7777',
        email: 'robert.davis@example.com',
        address: '456 Elm St, City, State',
        linkedIn: 'linkedin.com/in/robertdavis',
        twitter: '@robertdavis',
        instagram: '@robertdavis_insta',
      },
      {
        picture: '/assets/images/avatar/man.png',
        full_name: 'Carlos Rodriguez',
        job_title: 'Software Developer',
        country: 'mx',
        status: 'Active',
        phone: '55-1234-5678',
        email: 'carlos.rodriguez@example.com',
        address: 'Av. Reforma 123, Ciudad de México',
        linkedIn: 'linkedin.com/in/carlosrodriguez',
        twitter: '@carlosrodriguez',
        instagram: '@carlosrodriguez_insta',
      },
      {
        picture: '',
        full_name: 'Emma Watson',
        job_title: 'Marketing Coordinator',
        country: 'gb',
        status: 'Inactive',
        phone: '44-9876-543210',
        email: 'emma.watson@example.com',
        address: 'Abbey Road 123, Liverpool',
        linkedIn: 'linkedin.com/in/emmawatson',
        twitter: '@emmawatson',
        instagram: '@emmawatson_insta',
      },
      {
        picture: '',
        full_name: 'Michael Chen',
        job_title: 'Software Developer',
        country: 'ca',
        status: 'Inactive',
        phone: '777-555-1234',
        email: 'michael.chen@example.com',
        address: '222 Cedar St, City, Province',
        linkedIn: 'linkedin.com/in/michaelchen',
        twitter: '@michaelchen',
        instagram: '@michaelchen_insta',
      },
      {
        picture: '',
        full_name: 'John Doe',
        job_title: 'Software Engineer',
        country: 'ca',
        status: 'Inactive',
        phone: '123-456-7890',
        email: 'john.doe@example.com',
        address: '123 Main St, City, Province',
        linkedIn: 'linkedin.com/in/johndoe',
        twitter: '@johndoe',
        instagram: '@johndoe_insta',
      },
      {
        picture: '/assets/images/avatar/man.png',
        full_name: 'Elena Navarro',
        job_title: 'HR Manager',
        country: 'es',
        status: 'Active',
        phone: '34-999-000111',
        email: 'elena.navarro@example.com',
        address: 'Carrer del Mar 234, Bilbao',
        linkedIn: 'linkedin.com/in/elenanavarro',
        twitter: '@elenanavarro',
        instagram: '@elenanavarro_insta',
      },
      {
        picture: '/assets/images/avatar/man.png',
        full_name: 'Alice Johnson',
        job_title: 'Data Scientist',
        country: 'ca',
        status: 'Inactive',
        phone: '987-654-3210',
        email: 'alice.johnson@example.com',
        address: '456 Oak St, City, Province',
        linkedIn: 'linkedin.com/in/alicejohnson',
        twitter: '@alicejohnson',
        instagram: '@alicejohnson_insta',
      },
      {
        picture: '/assets/images/avatar/man.png',
        full_name: 'David Wilson',
        job_title: 'Product Manager',
        country: 'ca',
        status: 'Inactive',
        phone: '555-123-4567',
        email: 'david.wilson@example.com',
        address: '789 Maple St, City, Province',
        linkedIn: 'linkedin.com/in/davidwilson',
        twitter: '@davidwilson',
        instagram: '@davidwilson_insta',
      },
      {
        picture: '/assets/images/avatar/man.png',
        full_name: 'Olivia White',
        job_title: 'HR Specialist',
        country: 'us',
        status: 'Active',
        phone: '444-555-6666',
        email: 'olivia.white@example.com',
        address: '321 Oak St, City, State',
        linkedIn: 'linkedin.com/in/oliviawhite',
        twitter: '@oliviawhite',
        instagram: '@oliviawhite_insta',
      },
      {
        picture: '',
        full_name: 'Daniel Miller',
        job_title: 'Sales Representative',
        country: 'us',
        status: 'Inactive',
        phone: '777-888-9999',
        email: 'daniel.miller@example.com',
        address: '101 Cedar St, City, State',
        linkedIn: 'linkedin.com/in/danielmiller',
        twitter: '@danielmiller',
        instagram: '@danielmiller_insta',
      },
      {
        picture: '',
        full_name: 'Sophia Brown',
        job_title: 'UX Designer',
        country: 'us',
        status: 'Active',
        phone: '123-456-7890',
        email: 'sophia.brown@example.com',
        address: '567 Maple St, City, State',
        linkedIn: 'linkedin.com/in/sophiabrown',
        twitter: '@sophiabrown',
        instagram: '@sophiabrown_insta',
      },
      {
        picture: '',
        full_name: 'Pierre Dubois',
        job_title: 'Marketing Specialist',
        country: 'fr',
        status: 'Active',
        phone: '33-9876-5432',
        email: 'pierre.dubois@example.com',
        address: 'Avenue des Arts 456, Lyon',
        linkedIn: 'linkedin.com/in/pierredubois',
        twitter: '@pierredubois',
        instagram: '@pierredubois_insta',
      },
      {
        picture: '/assets/images/avatar/man.png',
        full_name: 'Miguel Hernández',
        job_title: 'Financial Analyst',
        country: 'mx',
        status: 'Active',
        phone: '33-5555-1234',
        email: 'miguel.hernandez@example.com',
        address: 'Av. Hidalgo 789, Monterrey',
        linkedIn: 'linkedin.com/in/miguelhernandez',
        twitter: '@miguelhernandez',
        instagram: '@miguelhernandez_insta',
      },
      {
        picture: '/assets/images/avatar/man.png',
        full_name: 'Ana Rodriguez',
        job_title: 'UX/UI Designer',
        country: 'es',
        status: 'Inactive',
        phone: '34-555-123456',
        email: 'ana.rodriguez@example.com',
        address: 'Plaza de España 789, Seville',
        linkedIn: 'linkedin.com/in/ana-rodriguez',
        twitter: '@anarodriguez',
        instagram: '@anarodriguez_insta',
      },
      {
        picture: '/assets/images/avatar/man.png',
        full_name: 'Ana Torres',
        job_title: 'Human Resources Manager',
        country: 'mx',
        status: 'Active',
        phone: '81-7777-8888',
        email: 'ana.torres@example.com',
        address: 'Paseo de la Reforma 101, Ciudad de México',
        linkedIn: 'linkedin.com/in/anatorres',
        twitter: '@anatorres',
        instagram: '@anatorres_insta',
      },
      {
        picture: '',
        full_name: 'Javier García',
        job_title: 'Sales Engineer',
        country: 'mx',
        status: 'Active',
        phone: '33-9999-0000',
        email: 'javier.garcia@example.com',
        address: 'Av. Benito Juárez 234, Guadalajara',
        linkedIn: 'linkedin.com/in/javiergarcia',
        twitter: '@javiergarcia',
        instagram: '@javiergarcia_insta',
      },
      {
        picture: '/assets/images/avatar/man.png',
        full_name: 'Jane Smith',
        job_title: 'Marketing Manager',
        country: 'us',
        status: 'Active',
        phone: '111-222-3333',
        email: 'jane.smith@example.com',
        address: '789 Pine St, City, State',
        linkedIn: 'linkedin.com/in/janesmith',
        twitter: '@janesmith',
        instagram: '@janesmith_insta',
      },
      {
        picture: '/assets/images/avatar/man.png',
        full_name: 'Sophie Martin',
        job_title: 'Software Developer',
        country: 'fr',
        status: 'Active',
        phone: '33-1234-5678',
        email: 'sophie.martin@example.com',
        address: 'Rue de la Liberté 123, Paris',
        linkedIn: 'linkedin.com/in/sophiemartin',
        twitter: '@sophiemartin',
        instagram: '@sophiemartin_insta',
      },
      {
        picture: '/assets/images/avatar/man.png',
        full_name: 'Camille Lefevre',
        job_title: 'UX/UI Designer',
        country: 'fr',
        status: 'Active',
        phone: '33-5555-1234',
        email: 'camille.lefevre@example.com',
        address: 'Boulevard de la Paix 789, Nice',
        linkedIn: 'linkedin.com/in/camillelefevre',
        twitter: '@camillelefevre',
        instagram: '@camillelefevre_insta',
      },
      {
        picture: '',
        full_name: 'Javier Moreno',
        job_title: 'Financial Analyst',
        country: 'es',
        status: 'Active',
        phone: '34-777-888999',
        email: 'javier.moreno@example.com',
        address: 'Calle de la Luna 101, Valencia',
        linkedIn: 'linkedin.com/in/javiermoreno',
        twitter: '@javiermoreno',
        instagram: '@javiermoreno_insta',
      },
      {
        picture: '/assets/images/avatar/man.png',
        full_name: 'Lucas Chevalier',
        job_title: 'Financial Analyst',
        country: 'fr',
        status: 'Active',
        phone: '33-7777-8888',
        email: 'lucas.chevalier@example.com',
        address: 'Place du Commerce 101, Marseille',
        linkedIn: 'linkedin.com/in/lucaschevalier',
        twitter: '@lucaschevalier',
        instagram: '@lucaschevalier_insta',
      },
      {
        picture: '/assets/images/avatar/man.png',
        full_name: 'Isabelle Rousseau',
        job_title: 'HR Manager',
        country: 'fr',
        status: 'Active',
        phone: '33-9999-0000',
        email: 'isabelle.rousseau@example.com',
        address: 'Quai de la Seine 234, Lille',
        linkedIn: 'linkedin.com/in/isabellerousseau',
        twitter: '@isabellerousseau',
        instagram: '@isabellerousseau_insta',
      },
      {
        picture: '/assets/images/avatar/man.png',
        full_name: 'James Turner',
        job_title: 'Software Engineer',
        country: 'gb',
        status: 'Active',
        phone: '44-1234-567890',
        email: 'james.turner@example.com',
        address: 'Baker Street 221B, London',
        linkedIn: 'linkedin.com/in/jamesturner',
        twitter: '@jamesturner',
        instagram: '@jamesturner_insta',
      },
      {
        picture: '',
        full_name: 'Elena Bianchi',
        job_title: 'Marketing Specialist',
        country: 'it',
        status: 'Active',
        phone: '39-987-6543210',
        email: 'elena.bianchi@example.com',
        address: 'Piazza del Duomo 456, Milan',
        linkedIn: 'linkedin.com/in/elenabianchi',
        twitter: '@elenabianchi',
        instagram: '@elenabianchi_insta',
      },
      {
        picture: '/assets/images/avatar/man.png',
        full_name: 'William Knight',
        job_title: 'Product Manager',
        country: 'gb',
        status: 'Active',
        phone: '44-5555-123456',
        email: 'william.knight@example.com',
        address: 'High Street 456, Manchester',
        linkedIn: 'linkedin.com/in/williamknight',
        twitter: '@williamknight',
        instagram: '@williamknight_insta',
      },
      {
        picture: '/assets/images/avatar/man.png',
        full_name: 'Charlotte Brown',
        job_title: 'UX Designer',
        country: 'gb',
        status: 'Active',
        phone: '44-7777-888999',
        email: 'charlotte.brown@example.com',
        address: 'Park Avenue 789, Birmingham',
        linkedIn: 'linkedin.com/in/charlottebrown',
        twitter: '@charlottebrown',
        instagram: '@charlottebrown_insta',
      },
      {
        picture: '/assets/images/avatar/man.png',
        full_name: 'Oliver Taylor',
        job_title: 'Financial Analyst',
        country: 'gb',
        status: 'Active',
        phone: '44-9999-000111',
        email: 'oliver.taylor@example.com',
        address: 'Victoria Street 101, Edinburgh',
        linkedIn: 'linkedin.com/in/olivertaylor',
        twitter: '@olivertaylor',
        instagram: '@olivertaylor_insta',
      },
      {
        picture: '',
        full_name: 'Giuseppe Rossi',
        job_title: 'Software Developer',
        country: 'it',
        status: 'Active',
        phone: '39-123-4567890',
        email: 'giuseppe.rossi@example.com',
        address: 'Via Roma 123, Rome',
        linkedIn: 'linkedin.com/in/giusepperossi',
        twitter: '@giusepperossi',
        instagram: '@giusepperossi_insta',
      },
      {
        picture: '/assets/images/avatar/man.png',
        full_name: 'Marco Ferrari',
        job_title: 'UX/UI Designer',
        country: 'it',
        status: 'Inactive',
        phone: '39-555-1234567',
        email: 'marco.ferrari@example.com',
        address: 'Corso Vittorio Emanuele 789, Florence',
        linkedIn: 'linkedin.com/in/marcoferrari',
        twitter: '@marcoferrari',
        instagram: '@marcoferrari_insta',
      },
      {
        picture: '/assets/images/avatar/man.png',
        full_name: 'Sofia Ricci',
        job_title: 'Financial Analyst',
        country: 'it',
        status: 'Active',
        phone: '39-777-8889999',
        email: 'sofia.ricci@example.com',
        address: 'Viale di Trastevere 101, Naples',
        linkedIn: 'linkedin.com/in/sofiaricci',
        twitter: '@sofiaricci',
        instagram: '@sofiaricci_insta',
      },
      {
        picture: '/assets/images/avatar/man.png',
        full_name: 'Luca Moretti',
        job_title: 'HR Manager',
        country: 'it',
        status: 'Inactive',
        phone: '39-999-0001111',
        email: 'luca.moretti@example.com',
        address: 'Via San Pietro 234, Venice',
        linkedIn: 'linkedin.com/in/lucamoretti',
        twitter: '@lucamoretti',
        instagram: '@lucamoretti_insta',
      },

      // Spain
      {
        picture: '',
        full_name: 'Maria Garcia',
        job_title: 'Software Engineer',
        country: 'es',
        status: 'Active',
        phone: '34-123-456789',
        email: 'maria.garcia@example.com',
        address: 'Calle Mayor 123, Madrid',
        linkedIn: 'linkedin.com/in/mariagarcia',
        twitter: '@mariagarcia',
        instagram: '@mariagarcia_insta',
      },
      {
        picture: '/assets/images/avatar/man.png',
        full_name: 'Sofía López',
        job_title: 'Graphic Designer',
        country: 'mx',
        status: 'Active',
        phone: '55-9876-5432',
        email: 'sofia.lopez@example.com',
        address: 'Calle Juárez 456, Guadalajara',
        linkedIn: 'linkedin.com/in/sofialopez',
        twitter: '@sofialopez',
        instagram: '@sofialopez_insta',
      },
      {
        picture: '',
        full_name: 'Carlos Fernandez',
        job_title: 'Marketing Specialist',
        country: 'es',
        status: 'Inactive',
        phone: '34-987-654321',
        email: 'carlos.fernandez@example.com',
        address: 'Avenida del Sol 456, Barcelona',
        linkedIn: 'linkedin.com/in/carlosfernandez',
        twitter: '@carlosfernandez',
        instagram: '@carlosfernandez_insta',
      },
    ];

    return of(values);
  }
}
